version: '2'

networks:
  mcnet:
    driver: bridge

volumes:
  pgdata:
    driver: local
  webdata:
    driver: local

services:
  proxy:
    hostname: apache
    build: ../letsencrypt-proxy-docker
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webapp
    networks:
      - mcnet
    environment:
      # Set your host
      - HOST=dev.magisa.org
      - PORT=8080
      # Set your email
      - EMAIL=mbjones.89@gmail.com
      # Turn on production mode
      #- MODE=PRODUCTION
    links:
      - webapp:proxied
  webapp:
    hostname: metacat
    image: metacat:2.8.4
    depends_on:
      - postgres
    networks:
      - mcnet
    ports:
      - '8080:8080'
    volumes:
      - webdata:/var/metacat
    environment:
      ADMIN: ${ADMIN}
      ADMINPASS: ${ADMINPASS}
      POSTGRES_DB: ${PGDB}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASS}
    links:
      - postgres
  postgres:
    hostname: postgres
    image: postgres
    networks:
      - mcnet
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/pgdata
    environment:
      POSTGRES_PASSWORD: ${PGPASS}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDB}
      PGDATA: '/pgdata'
