version: '2'

networks:
  mcnet:
    driver: bridge

volumes:
  pgdata:
    driver: local
  webdata:
    driver: local

services:
  webapp:
    image: metacat:2.8.4
    depends_on:
      - postgres
    networks:
      - mcnet
    ports:
      - '8080:8080'
    volumes:
      - webdata:/var/metacat
      - ${HOME}/tomcat/apache-tomcat-8.0.30/webapps:/usr/local/tomcat/webapps
    environment:
      ADMIN: ${ADMIN}
      ADMINPASS: ${ADMINPASS}
      POSTGRES_DB: ${PGDB}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASS}
  postgres:
    image: postgres
    networks:
      - mcnet
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/pgdata
    environment:
      POSTGRES_PASSWORD: ${PGPASS}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDB}
      PGDATA: '/pgdata'
